import { Router } from "express";
import type { Db } from "@paperclipai/db";
import { logger } from "../middleware/logger.js";
import { workerCallbackStore } from "../services/worker-callback-store.js";

// Worker-callback routes for the claude_remote adapter. A remote worker
// (Fly Machine) POSTs its final result here; the adapter polls /status.
// Auth: bearer agent API key (enforced by actorMiddleware — we just check
// req.actor.type === "agent" here).
//
// No runId ↔ agent ownership check today: the runId is generated by the
// adapter and never leaves the control plane + spawned machine. Revisit
// when workers become user-addressable.
export function workerCallbackRoutes(_db: Db) {
  const router = Router();

  router.post("/worker-callbacks/:runId/complete", async (req, res) => {
    if (req.actor.type !== "agent") {
      res.status(401).json({ error: "agent authentication required" });
      return;
    }
    const runId = (req.params.runId ?? "").trim();
    if (!runId) {
      res.status(400).json({ error: "runId required" });
      return;
    }

    const body = (req.body ?? {}) as Record<string, unknown>;
    const exitCode =
      typeof body.exitCode === "number" ? body.exitCode : null;
    const signal = typeof body.signal === "string" ? body.signal : null;
    const timedOut = body.timedOut === true;
    const stdout = typeof body.stdout === "string" ? body.stdout : "";
    const stderr = typeof body.stderr === "string" ? body.stderr : "";
    const errorMessage =
      typeof body.errorMessage === "string" ? body.errorMessage : null;
    const sessionParams =
      body.sessionParams && typeof body.sessionParams === "object" && !Array.isArray(body.sessionParams)
        ? (body.sessionParams as Record<string, unknown>)
        : null;

    workerCallbackStore.putCompletion({
      runId,
      exitCode,
      signal,
      timedOut,
      stdout,
      stderr,
      errorMessage,
      sessionParams,
      receivedAt: Date.now(),
    });

    logger.info(
      { runId, exitCode, signal, stdoutBytes: stdout.length },
      "[worker-callback] completion received",
    );

    res.status(204).end();
  });

  router.get("/worker-callbacks/:runId/status", async (req, res) => {
    const actor = req.actor;
    if (actor.type !== "agent" && actor.type !== "board") {
      res.status(401).json({ error: "authentication required" });
      return;
    }
    const runId = (req.params.runId ?? "").trim();
    if (!runId) {
      res.status(400).json({ error: "runId required" });
      return;
    }
    const entry = workerCallbackStore.getCompletion(runId);
    if (!entry) {
      res.status(404).json({ status: "pending" });
      return;
    }
    res.json({ status: "complete", completion: entry });
  });

  return router;
}
